### ISSUE TITLE
Current release have some fatal error.

### ISSUE THREAD

**Issue by kxxoling** [editorconfig/editorconfig-core-py#12]
Just install the newest package from PyPI, which is version 0.12.0, contains fatal error when I try to run ``editorconfig /path/to/README.md`` occurs:

```traceback
Traceback (most recent call last):
  File "/usr/local/bin/editorconfig", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/editorconfig/main.py", line 73, in main
    print(str(e))
UnboundLocalError: local variable 'e' referenced before assignment
```

Which I found it's this line in the project: https://github.com/editorconfig/editorconfig-core-py/blob/master/editorconfig/main.py#L72

It's fixed on GitHub, but released with issue. Please release a new version to fix this issue.

**Comment by treyhunner** [comment]
@xuhdev release made
