### ISSUE TITLE
Determine support for Python 3.5–3.8

### ISSUE THREAD

**Issue by bignose-debian** [editorconfig/editorconfig-core-py#19]
The latest release “0.12.1” metadata (the trove classifiers) declares support for Python 3 versions 3.2, 3.3, 3.4.

Please determine support for later versions of Python 3 that exist: 3.5, 3.6, 3.7; and declare (or not, if the library is incompatible) support in the trove classifiers, in a new release to PyPI.

**Comment by xuhdev** [comment]
Thank you for your report. Will solve in the next few days.
