### ISSUE TITLE
Use standard library ‘OrderedDict’ type

### ISSUE THREAD

**Issue by bignose-debian** [editorconfig/editorconfig-core-py#21]
With the removal of Python 2.6 support (commit 1a1689774bb33fc66d1387ef1f3f9bfef1b7204d), the `collections.OrderedDict` type is now available to every supported Python version.

We can use that type from the standard library, and remove the bundled third-party ‘odict.py’ library.

**Comment by bignose-debian** [comment]
I have an implementation to address this, in the branch ‘[wip/issue/github-21/collections-ordereddict](https://salsa.debian.org/bignose/editorconfig-core-py/tree/wip/issue/github-21/collections-ordereddict)’ of my personal fork repository at https://salsa.debian.org/bignose/editorconfig-core-py.git (currently clean against commit 1a1689774bb33fc66d1387ef1f3f9bfef1b7204d).

**Comment by xuhdev** [comment]
Thanks! Can you make a pull request, so we can watch the testing output?

**Comment by bignose-debian** [comment]
On 07-Feb-2018, Hong wrote:
> Thanks! Can you make a pull request, so we can watch the testing
> output?

The GitHub-specific feature is inadequate for this, because AFAICT
that fails when the repository is not on GitHub (I don't use GitHub
for any repositories).

Git is a decentralised system, so here is a pull request generated by
‘git request-pull’:


The following changes since commit 1a1689774bb33fc66d1387ef1f3f9bfef1b7204d:

  Declare support for Python 3.5 and 3.6, and remove 2.6, 3.2, and 3.3. (2018-02-06 00:17:46 -0800)

are available in the Git repository at:

  https://salsa.debian.org/bignose/editorconfig-core-py.git wip/issue/github-21/collections-ordereddict

for you to fetch changes up to 9a3c7b30511e06a011653cd34f69bdefcf0380db:

  Remove unused ‘odict’ module. (2018-02-07 09:27:56 +1100)

----------------------------------------------------------------
(from the branch description for wip/issue/github-21/collections-ordereddict local branch)

Use the standard library ‘OrderedDict’ class.

GitHub: issue #21.

----------------------------------------------------------------
Ben Finney (3):
      Sort import statements, one per line within groups.
      Use ‘OrderedDict’ from standard library.
      Remove unused ‘odict’ module.

 docs/conf.py            |   4 +-
 editorconfig/compat.py  |   1 +
 editorconfig/fnmatch.py |   1 +
 editorconfig/handler.py |   2 +-
 editorconfig/ini.py     |   8 +-
 editorconfig/main.py    |   6 +-
 editorconfig/odict.py   | 897 ------------------------------------------------
 setup.py                |   1 +
 8 files changed, 14 insertions(+), 906 deletions(-)
 delete mode 100644 editorconfig/odict.py


-- 
 \     “When people believe that they have absolute knowledge, with no |
  `\     test in reality, this [the Auschwitz crematorium] is how they |
_o__)             behave.” —Jacob Bronowski, _The Ascent of Man_, 1973 |
Ben Finney <ben@benfinney.id.au>

**Comment by xuhdev** [comment]
Cool, all tests passed on my system. Do you think it's ready to merge, or you have something else you wanna add?

**Comment by bignose-debian** [comment]
On 07-Feb-2018, Hong wrote:

> Cool, all tests passed on my system.

Thanks for testing. (I ran the tests on my system but got four
failures, *before* making changes; fortunately, there were no extra
failures after the changes :-)

> Do you think it's ready to merge, or you have something else you
> wanna add?

If you're happy with it I think it's ready to merge.

-- 
 \       “Pinky, are you pondering what I'm pondering?” “Well, I think |
  `\        so, Brain, but I can't memorize a whole opera in Yiddish.” |
_o__)                                           —_Pinky and The Brain_ |
Ben Finney <ben@benfinney.id.au>

**Comment by xuhdev** [comment]
Merged in 9a3c7b30511e06a011653cd34f69bdefcf0380db . Thanks!
