### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by jefferyto** [editorconfig/editorconfig-core-py#23]
It seems recent releases are not tagged:
* The last release to be tagged was [0.12.0](https://github.com/editorconfig/editorconfig-core-py/tree/v0.12.0).
* There is already [an issue dealing with 0.12.1](https://github.com/editorconfig/editorconfig-core-py/issues/14).
* PyPI has a [0.12.2](https://pypi.org/project/EditorConfig/0.12.2/) - it appears to be 596da5e06ebee05bdbdc6224203c79c4d3c6486a but there is no tag.

Tagging a commit adds an entry to the [releases page](https://github.com/editorconfig/editorconfig-core-py/releases), and in general signifies that a particular version of the code is ready for general use.

**Comment by greut** [comment]
The missing tags have been created, correctly I hope. Although, I don't have any access to PyPI to push any new ones there.
