### ISSUE TITLE
Grant a recommended free-software license

### ISSUE THREAD

**Issue by bignose-debian** [editorconfig/editorconfig-core-py#26]
Thank you for making this code base free software. The granted license, though, is not suitable for anything other than Python itself. (See the PSF's own FAQ for [why not to use the PSF license for other code](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#Why_can.27t_I_contribute_code_under_the_PSF_License.3F).)

Instead, please release this library under a recommended free-software license (not the PSF license), such as the [GNU General Public License 3.0-or-later](https://www.gnu.org/licenses/quick-guide-gplv3.html) or the Apache License 2.0. The PSF has a [brief answer for this too](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#Which_open_source_license_should_I_use.3F).

**Comment by xuhdev** [comment]
Our license is 2-clause BSD, please see the `COPYING` file.

Some files are under PSF because they were copied out from Python std library.
