### ISSUE TITLE
Please package the test suite to your tarball

### ISSUE THREAD

**Issue by mcepl** [editorconfig/editorconfig-core-py#37]
I would like to fix packaging for OpenSUSE, but your release tarball does not contain the tests directory. Could you please distribute them as well?

**Comment by greut** [comment]
My two cents, here. As the test suite requires cmake/ctest; it doesn't seem very convenient considering the Python world.

> This of course only works, if the package supports regular python unittests. If this call does not work one has to dig around checking various files in the development repository like .travis.yml or tox.ini.
>
> https://en.opensuse.org/openSUSE:Packaging_Python#Running_tests

**Comment by xuhdev** [comment]
Could you grab the source by running

    git clone --recursive https://github.com/editorconfig/editorconfig-core-py
    git checkout v0.12.3

? Unfortunately, github's [release page](https://github.com/editorconfig/editorconfig-core-py/releases) doesn't generate tarballs with submodules.

**Comment by mcepl** [comment]
Just running
```
cmake .
export PYTHONPATH=$(pwd)
ctest -VV --output-on-failure .
```
got me almost working tests (see complete [build log](https://github.com/editorconfig/editorconfig-core-py/files/7083006/_log.txt)) with these failures:
```
[   33s] test 113
[   33s]         Start 113: star_star_over_separator7
[   33s]
[   33s] 113: Test command: /usr/bin/python3.9 "-m" "editorconfig" "-f" "star_star.in" "/home/abuild/rpmbuild/BUILD/editorconfig-core-py-0.12.3/tests/glob/b/z.c"
[   33s] 113: Test timeout computed to be: 10000000
[   33s] 113: key1=value1
[   33s] 113: key2=value2
[   33s] 113/197 Test #113: star_star_over_separator7 .................***Failed  Required regular expression not found. Regex=[^key2=value2[ 	
]*$ 33s]
[   33s] ]  0.04 sec
[   33s] key1=value1
[   33s] key2=value2
[   33s]
```
Do I miss some header file or something?

**Comment by xuhdev** [comment]
I just tested it on my machine and all tests passed. Could you try run `git submodule update --init --recursive` once to make sure the test submodule version matches?

**Comment by xuhdev** [comment]
We have enabled github actions and it's passing. Closing now.
