### ISSUE TITLE
add python 3.12 support

### ISSUE THREAD

**Issue by blshkv** [editorconfig/editorconfig-core-py#47]
Thanks.

**Comment by greut** [comment]
@blshkv from what I can tell, 3.12 is supported. Did you encounter any troubles?

**Comment by blshkv** [comment]
I haven't experienced any issues, but it would be good to see the updated list at:
https://pypi.org/project/EditorConfig/

According to the list on that page, [Python :: 3.9] is the only supported

**Comment by blshkv** [comment]
Thank you for fixing the issue. Could you release a newer version please?

**Comment by xuhdev** [comment]
Sorry for the delay. Done!

**Comment by blshkv** [comment]
Great, thanks!
