### ISSUE TITLE
editorconfig-core-py-0.12.3 installs deprecated .egg/.egg-info (GCC-14-SYSTEM)

### ISSUE THREAD

**Issue by blshkv** [editorconfig/editorconfig-core-py#49]
I know nothing about, just trying to close the following bug:
https://bugs.gentoo.org/921652

**Comment by xuhdev** [comment]
I don't this issue belongs here. Rather, it's likely a bug in Gentoo's ebuild or some other packaging files. See [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)

**Comment by blshkv** [comment]
no, it is not a Gentoo bug. See:
https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/
```[PEP 715](https://peps.python.org/pep-0715/), deprecating bdist_egg/.egg```

**Comment by blshkv** [comment]
hm... I converted the ebuild to PEP517, and the message is gone. So you must be right, this is a gentoo bug.
